/** US cities for the Hometown autocomplete.
 *
 * Hometown is a *string match signal* in the connections engine, so it needs
 * NAMES ONLY — no coordinates. (Coordinates belong to the home-base picker,
 * lib/places.ts, which is a different concept: where your feed is scoped.)
 *
 * Curated to the metros + college towns people most commonly move from/to.
 * Not exhaustive by design — the ComboField free-text fallback covers anything
 * not listed, so a missing town never blocks anyone. */
export const CITIES: readonly string[] = [
  // Northeast & Mid-Atlantic
  "New York, NY",
  "Brooklyn, NY",
  "Buffalo, NY",
  "Rochester, NY",
  "Albany, NY",
  "Boston, MA",
  "Cambridge, MA",
  "Worcester, MA",
  "Providence, RI",
  "Hartford, CT",
  "New Haven, CT",
  "Stamford, CT",
  "Portland, ME",
  "Manchester, NH",
  "Burlington, VT",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Allentown, PA",
  "Newark, NJ",
  "Jersey City, NJ",
  "Princeton, NJ",
  "Washington, DC",
  "Baltimore, MD",
  "Wilmington, DE",
  // South & Southeast
  "Richmond, VA",
  "Virginia Beach, VA",
  "Arlington, VA",
  "Charlottesville, VA",
  "Charlotte, NC",
  "Raleigh, NC",
  "Durham, NC",
  "Greensboro, NC",
  "Asheville, NC",
  "Columbia, SC",
  "Charleston, SC",
  "Atlanta, GA",
  "Savannah, GA",
  "Athens, GA",
  "Jacksonville, FL",
  "Miami, FL",
  "Orlando, FL",
  "Tampa, FL",
  "Tallahassee, FL",
  "Gainesville, FL",
  "Nashville, TN",
  "Memphis, TN",
  "Knoxville, TN",
  "Chattanooga, TN",
  "Louisville, KY",
  "Lexington, KY",
  "Birmingham, AL",
  "Montgomery, AL",
  "Huntsville, AL",
  "New Orleans, LA",
  "Baton Rouge, LA",
  "Jackson, MS",
  "Little Rock, AR",
  // Midwest
  "Chicago, IL",
  "Springfield, IL",
  "Indianapolis, IN",
  "Bloomington, IN",
  "Columbus, OH",
  "Cleveland, OH",
  "Cincinnati, OH",
  "Toledo, OH",
  "Detroit, MI",
  "Ann Arbor, MI",
  "Grand Rapids, MI",
  "Milwaukee, WI",
  "Madison, WI",
  "Minneapolis, MN",
  "St. Paul, MN",
  "Des Moines, IA",
  "Iowa City, IA",
  "St. Louis, MO",
  "Kansas City, MO",
  "Columbia, MO",
  "Omaha, NE",
  "Lincoln, NE",
  "Wichita, KS",
  "Fargo, ND",
  "Sioux Falls, SD",
  // Southwest & Mountain
  "Austin, TX",
  "Dallas, TX",
  "Houston, TX",
  "San Antonio, TX",
  "Fort Worth, TX",
  "El Paso, TX",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Albuquerque, NM",
  "Santa Fe, NM",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Scottsdale, AZ",
  "Tempe, AZ",
  "Las Vegas, NV",
  "Reno, NV",
  "Denver, CO",
  "Boulder, CO",
  "Colorado Springs, CO",
  "Fort Collins, CO",
  "Salt Lake City, UT",
  "Provo, UT",
  "Boise, ID",
  // West Coast & Pacific
  "Los Angeles, CA",
  "San Diego, CA",
  "San Francisco, CA",
  "Oakland, CA",
  "San Jose, CA",
  "Sacramento, CA",
  "Fresno, CA",
  "Long Beach, CA",
  "Berkeley, CA",
  "Santa Barbara, CA",
  "Santa Monica, CA",
  "Pasadena, CA",
  "Irvine, CA",
  "Seattle, WA",
  "Tacoma, WA",
  "Spokane, WA",
  "Bellevue, WA",
  "Portland, OR",
  "Eugene, OR",
  "Salem, OR",
  "Anchorage, AK",
  "Honolulu, HI",
];
