/** US colleges & universities for the College autocomplete.
 *
 * The connections engine matches `college` by EXACT string equality, so the
 * point of this list is canonicalisation: two alumni who both pick
 * "Ohio State University" store the identical string and light up the
 * shared-background tier — where "Ohio State", "OSU", and "the ohio state
 * university" typed by hand never would.
 *
 * Recognizable names only (flagships, big privates, notable LACs) — not the
 * full ~6,000-institution IPEDS set. The ComboField free-text fallback covers
 * everything else, so an unlisted school never blocks sign-up. Swap in the full
 * Dept. of Education College Scorecard list when this graduates out of the
 * prototype. */
export const COLLEGES: readonly string[] = [
  // Ivy League
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "Brown University",
  "Cornell University",
  "Dartmouth College",
  "University of Pennsylvania",
  // Other private research universities
  "Stanford University",
  "Massachusetts Institute of Technology",
  "California Institute of Technology",
  "Duke University",
  "Northwestern University",
  "University of Chicago",
  "Johns Hopkins University",
  "Vanderbilt University",
  "Rice University",
  "Emory University",
  "Georgetown University",
  "University of Notre Dame",
  "Carnegie Mellon University",
  "Washington University in St. Louis",
  "New York University",
  "University of Southern California",
  "Boston University",
  "Boston College",
  "Northeastern University",
  "Tufts University",
  "Brandeis University",
  "University of Rochester",
  "Case Western Reserve University",
  "Wake Forest University",
  "Tulane University",
  "Southern Methodist University",
  "Baylor University",
  "Texas Christian University",
  "University of Miami",
  "Syracuse University",
  "Fordham University",
  "Villanova University",
  "Lehigh University",
  "Drexel University",
  "George Washington University",
  "American University",
  "Howard University",
  "Pepperdine University",
  "Santa Clara University",
  "Gonzaga University",
  "Marquette University",
  "DePaul University",
  "Loyola University Chicago",
  "Saint Louis University",
  "Creighton University",
  "Brigham Young University",
  // Public flagships & major state universities
  "University of Alabama",
  "Auburn University",
  "University of Arizona",
  "Arizona State University",
  "University of Arkansas",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Santa Barbara",
  "University of California, Santa Cruz",
  "University of California, Riverside",
  "San Diego State University",
  "San Jose State University",
  "California Polytechnic State University",
  "University of Colorado Boulder",
  "Colorado State University",
  "University of Connecticut",
  "University of Delaware",
  "University of Florida",
  "Florida State University",
  "University of Central Florida",
  "University of South Florida",
  "Florida International University",
  "University of Georgia",
  "Georgia Institute of Technology",
  "Georgia State University",
  "University of Hawaii",
  "University of Idaho",
  "University of Illinois Urbana-Champaign",
  "Illinois State University",
  "Indiana University Bloomington",
  "Purdue University",
  "University of Iowa",
  "Iowa State University",
  "University of Kansas",
  "Kansas State University",
  "University of Kentucky",
  "Louisiana State University",
  "University of Maine",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Michigan",
  "Michigan State University",
  "Wayne State University",
  "University of Minnesota",
  "University of Mississippi",
  "Mississippi State University",
  "University of Missouri",
  "University of Montana",
  "University of Nebraska–Lincoln",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of New Hampshire",
  "Rutgers University",
  "University of New Mexico",
  "University of North Carolina at Chapel Hill",
  "North Carolina State University",
  "University of North Dakota",
  "Ohio State University",
  "Ohio University",
  "Miami University",
  "University of Cincinnati",
  "University of Oklahoma",
  "Oklahoma State University",
  "University of Oregon",
  "Oregon State University",
  "Pennsylvania State University",
  "University of Pittsburgh",
  "Temple University",
  "University of Rhode Island",
  "University of South Carolina",
  "Clemson University",
  "University of Tennessee",
  "University of Texas at Austin",
  "Texas A&M University",
  "Texas Tech University",
  "University of Houston",
  "University of Utah",
  "Utah State University",
  "University of Vermont",
  "University of Virginia",
  "Virginia Tech",
  "Virginia Commonwealth University",
  "James Madison University",
  "George Mason University",
  "University of Washington",
  "Washington State University",
  "West Virginia University",
  "University of Wisconsin–Madison",
  "University of Wyoming",
  "University at Buffalo",
  "Stony Brook University",
  "Binghamton University",
  "Rutgers University–Newark",
  // Technology institutes
  "Rensselaer Polytechnic Institute",
  "Worcester Polytechnic Institute",
  "Stevens Institute of Technology",
  "Rochester Institute of Technology",
  "Illinois Institute of Technology",
  // Liberal arts colleges
  "Williams College",
  "Amherst College",
  "Swarthmore College",
  "Wellesley College",
  "Pomona College",
  "Claremont McKenna College",
  "Harvey Mudd College",
  "Middlebury College",
  "Bowdoin College",
  "Carleton College",
  "Colby College",
  "Bates College",
  "Hamilton College",
  "Davidson College",
  "Vassar College",
  "Oberlin College",
  "Grinnell College",
  "Colgate University",
  "Bucknell University",
  "Lafayette College",
  "Reed College",
  "Macalester College",
  "Smith College",
  "Mount Holyoke College",
  "Barnard College",
  "Haverford College",
  // Historically Black colleges & universities
  "Spelman College",
  "Morehouse College",
  "Florida A&M University",
  "North Carolina A&T State University",
];
