/** US colleges & universities for the College autocomplete.
 *
 * The connections engine matches `college` by EXACT string equality, so the
 * point of this list is canonicalisation: two alumni who both pick
 * "Ohio State University" store the identical string and light up the
 * shared-background tier — where "Ohio State", "OSU", and "the ohio state
 * university" typed by hand never would.
 *
 * Broad, recognizable coverage — flagships and big privates PLUS the regional
 * and directional state schools, Cal State / SUNY campuses, HBCUs, religious
 * universities, art/music/design schools, service academies, and large online
 * universities where most graduates actually come from (the wedge user is a
 * just-moved college grad, so their school is usually a state regional, not an
 * Ivy). This is still NOT the full ~6,000-institution IPEDS set — the
 * ComboField free-text fallback covers anything unlisted, so an unlisted school
 * never blocks sign-up. For the EXHAUSTIVE ~2,000 four-year set, run
 * `node scripts/build_colleges.mjs` in a Codespace (it needs network egress that
 * the browser sandbox doesn't have) and review the diff — it regenerates this
 * file from a public dataset. */
export const COLLEGES: readonly string[] = [
  // Ivy League
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "Brown University",
  "Cornell University",
  "Dartmouth College",
  "University of Pennsylvania",
  // Other private research universities
  "Stanford University",
  "Massachusetts Institute of Technology",
  "California Institute of Technology",
  "Duke University",
  "Northwestern University",
  "University of Chicago",
  "Johns Hopkins University",
  "Vanderbilt University",
  "Rice University",
  "Emory University",
  "Georgetown University",
  "University of Notre Dame",
  "Carnegie Mellon University",
  "Washington University in St. Louis",
  "New York University",
  "University of Southern California",
  "Boston University",
  "Boston College",
  "Northeastern University",
  "Tufts University",
  "Brandeis University",
  "University of Rochester",
  "Case Western Reserve University",
  "Wake Forest University",
  "Tulane University",
  "Southern Methodist University",
  "Baylor University",
  "Texas Christian University",
  "University of Miami",
  "Syracuse University",
  "Fordham University",
  "Villanova University",
  "Lehigh University",
  "Drexel University",
  "George Washington University",
  "American University",
  "Howard University",
  "Pepperdine University",
  "Santa Clara University",
  "Gonzaga University",
  "Marquette University",
  "DePaul University",
  "Loyola University Chicago",
  "Saint Louis University",
  "Creighton University",
  "Brigham Young University",
  // Public flagships & major state universities
  "University of Alabama",
  "Auburn University",
  "University of Arizona",
  "Arizona State University",
  "University of Arkansas",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Santa Barbara",
  "University of California, Santa Cruz",
  "University of California, Riverside",
  "San Diego State University",
  "San Jose State University",
  "California Polytechnic State University",
  "University of Colorado Boulder",
  "Colorado State University",
  "University of Connecticut",
  "University of Delaware",
  "University of Florida",
  "Florida State University",
  "University of Central Florida",
  "University of South Florida",
  "Florida International University",
  "University of Georgia",
  "Georgia Institute of Technology",
  "Georgia State University",
  "University of Hawaii",
  "University of Idaho",
  "University of Illinois Urbana-Champaign",
  "Illinois State University",
  "Indiana University Bloomington",
  "Purdue University",
  "University of Iowa",
  "Iowa State University",
  "University of Kansas",
  "Kansas State University",
  "University of Kentucky",
  "Louisiana State University",
  "University of Maine",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Michigan",
  "Michigan State University",
  "Wayne State University",
  "University of Minnesota",
  "University of Mississippi",
  "Mississippi State University",
  "University of Missouri",
  "University of Montana",
  "University of Nebraska–Lincoln",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of New Hampshire",
  "Rutgers University",
  "University of New Mexico",
  "University of North Carolina at Chapel Hill",
  "North Carolina State University",
  "University of North Dakota",
  "Ohio State University",
  "Ohio University",
  "Miami University",
  "University of Cincinnati",
  "University of Oklahoma",
  "Oklahoma State University",
  "University of Oregon",
  "Oregon State University",
  "Pennsylvania State University",
  "University of Pittsburgh",
  "Temple University",
  "University of Rhode Island",
  "University of South Carolina",
  "Clemson University",
  "University of Tennessee",
  "University of Texas at Austin",
  "Texas A&M University",
  "Texas Tech University",
  "University of Houston",
  "University of Utah",
  "Utah State University",
  "University of Vermont",
  "University of Virginia",
  "Virginia Tech",
  "Virginia Commonwealth University",
  "James Madison University",
  "George Mason University",
  "University of Washington",
  "Washington State University",
  "West Virginia University",
  "University of Wisconsin–Madison",
  "University of Wyoming",
  "University at Buffalo",
  "Stony Brook University",
  "Binghamton University",
  "Rutgers University–Newark",
  // Regional & directional public universities — where most grads actually come from
  "California State University, Long Beach",
  "California State University, Fullerton",
  "California State University, Northridge",
  "California State University, Sacramento",
  "California State University, Los Angeles",
  "California State University, Fresno",
  "California State University, San Bernardino",
  "California State University, Chico",
  "California State Polytechnic University, Pomona",
  "San Francisco State University",
  "University at Albany",
  "SUNY New Paltz",
  "SUNY Geneseo",
  "SUNY Oswego",
  "University of Texas at Dallas",
  "University of Texas at San Antonio",
  "University of Texas at El Paso",
  "University of Texas at Arlington",
  "University of North Texas",
  "Texas State University",
  "Sam Houston State University",
  "Stephen F. Austin State University",
  "Texas Woman's University",
  "Florida Atlantic University",
  "University of North Florida",
  "Florida Gulf Coast University",
  "Ball State University",
  "Indiana State University",
  "University of Illinois Chicago",
  "Northern Illinois University",
  "Southern Illinois University Carbondale",
  "Eastern Illinois University",
  "Western Illinois University",
  "Central Michigan University",
  "Eastern Michigan University",
  "Western Michigan University",
  "Grand Valley State University",
  "Oakland University",
  "Bowling Green State University",
  "Kent State University",
  "University of Toledo",
  "University of Akron",
  "Wright State University",
  "Cleveland State University",
  "Youngstown State University",
  "Northern Kentucky University",
  "Western Kentucky University",
  "Eastern Kentucky University",
  "Murray State University",
  "Wichita State University",
  "University of Northern Iowa",
  "Missouri State University",
  "University of Missouri–Kansas City",
  "University of Missouri–St. Louis",
  "University of Nebraska Omaha",
  "North Dakota State University",
  "South Dakota State University",
  "University of South Dakota",
  "University of Wisconsin–Milwaukee",
  "Boise State University",
  "New Mexico State University",
  "Northern Arizona University",
  "Montana State University",
  "Weber State University",
  "Utah Valley University",
  "University of Colorado Denver",
  "University of Colorado Colorado Springs",
  "Portland State University",
  "Western Washington University",
  "Eastern Washington University",
  "Central Washington University",
  "University of Alabama at Birmingham",
  "University of South Alabama",
  "Troy University",
  "Georgia Southern University",
  "Kennesaw State University",
  "University of West Georgia",
  "University of Tennessee at Chattanooga",
  "East Tennessee State University",
  "Middle Tennessee State University",
  "University of Memphis",
  "University of Louisville",
  "East Carolina University",
  "University of North Carolina at Charlotte",
  "University of North Carolina at Greensboro",
  "University of North Carolina Wilmington",
  "Appalachian State University",
  "College of Charleston",
  "Coastal Carolina University",
  "Winthrop University",
  "Old Dominion University",
  "Christopher Newport University",
  "William & Mary",
  "University of Mary Washington",
  "Radford University",
  "Marshall University",
  "University of Central Arkansas",
  "Arkansas State University",
  "University of Louisiana at Lafayette",
  "Louisiana Tech University",
  "University of New Orleans",
  "University of Southern Mississippi",
  "University of Massachusetts Boston",
  "University of Massachusetts Lowell",
  "University of Massachusetts Dartmouth",
  "Towson University",
  "University of Maryland, Baltimore County",
  "Salisbury University",
  "University of the District of Columbia",
  "West Chester University of Pennsylvania",
  "Montclair State University",
  "Rowan University",
  "The College of New Jersey",
  "Rutgers University–Camden",
  // Technology institutes
  "Rensselaer Polytechnic Institute",
  "Worcester Polytechnic Institute",
  "Stevens Institute of Technology",
  "Rochester Institute of Technology",
  "Illinois Institute of Technology",
  "New Jersey Institute of Technology",
  "Missouri University of Science and Technology",
  "Michigan Technological University",
  "Colorado School of Mines",
  "Florida Institute of Technology",
  "Embry–Riddle Aeronautical University",
  "Franklin W. Olin College of Engineering",
  "Wentworth Institute of Technology",
  // Liberal arts colleges
  "Williams College",
  "Amherst College",
  "Swarthmore College",
  "Wellesley College",
  "Pomona College",
  "Claremont McKenna College",
  "Harvey Mudd College",
  "Scripps College",
  "Pitzer College",
  "Middlebury College",
  "Bowdoin College",
  "Carleton College",
  "Colby College",
  "Bates College",
  "Hamilton College",
  "Davidson College",
  "Vassar College",
  "Oberlin College",
  "Grinnell College",
  "Colgate University",
  "Bucknell University",
  "Lafayette College",
  "Reed College",
  "Macalester College",
  "Smith College",
  "Mount Holyoke College",
  "Barnard College",
  "Haverford College",
  "Bryn Mawr College",
  "Occidental College",
  "Dickinson College",
  "Gettysburg College",
  "Franklin & Marshall College",
  "Muhlenberg College",
  "Kenyon College",
  "Denison University",
  "College of Wooster",
  "DePauw University",
  "Wabash College",
  "Earlham College",
  "Kalamazoo College",
  "Hope College",
  "Beloit College",
  "Lawrence University",
  "St. Olaf College",
  "Gustavus Adolphus College",
  "Knox College",
  "Luther College",
  "Whitman College",
  "Colorado College",
  "Lewis & Clark College",
  "Trinity College",
  "Connecticut College",
  "Skidmore College",
  "Union College",
  "Hobart and William Smith Colleges",
  "Sarah Lawrence College",
  "Bard College",
  "Sewanee: The University of the South",
  "Washington and Lee University",
  "Furman University",
  "Wofford College",
  "Rhodes College",
  "Centre College",
  // Other private colleges & universities
  "University of Richmond",
  "Saint Joseph's University",
  "Loyola University Maryland",
  "Loyola University New Orleans",
  "Loyola Marymount University",
  "University of San Diego",
  "University of San Francisco",
  "University of Portland",
  "University of Scranton",
  "University of Dayton",
  "Saint Mary's College of California",
  "Providence College",
  "College of the Holy Cross",
  "Fairfield University",
  "Sacred Heart University",
  "Quinnipiac University",
  "Duquesne University",
  "Seton Hall University",
  "The Catholic University of America",
  "Bentley University",
  "Babson College",
  "Emerson College",
  "Suffolk University",
  "Simmons University",
  "Stonehill College",
  "Clark University",
  "Yeshiva University",
  "Hofstra University",
  "Pace University",
  "Adelphi University",
  "St. John's University",
  "Ithaca College",
  "Marist College",
  "Manhattan College",
  "University of Denver",
  "University of Tulsa",
  "Drake University",
  "Butler University",
  "Valparaiso University",
  "Bradley University",
  "Xavier University",
  "Chapman University",
  "Mercer University",
  "Samford University",
  "Belmont University",
  "Lipscomb University",
  "Elon University",
  "High Point University",
  "Stetson University",
  "Rollins College",
  "Trinity University",
  "Biola University",
  "Azusa Pacific University",
  "Seattle Pacific University",
  "Seattle University",
  "Calvin University",
  "Taylor University",
  "Oral Roberts University",
  "Liberty University",
  "Wheaton College (Illinois)",
  "Marymount University",
  "Trinity Washington University",
  "Gallaudet University",
  // Historically Black colleges & universities
  "Spelman College",
  "Morehouse College",
  "Florida A&M University",
  "North Carolina A&T State University",
  "Hampton University",
  "Tuskegee University",
  "Xavier University of Louisiana",
  "Clark Atlanta University",
  "Jackson State University",
  "North Carolina Central University",
  "Prairie View A&M University",
  "Texas Southern University",
  "Tennessee State University",
  "Alabama A&M University",
  "Alabama State University",
  "Fisk University",
  "Morgan State University",
  "Bowie State University",
  "Delaware State University",
  "Norfolk State University",
  "Virginia State University",
  "Southern University and A&M College",
  "Grambling State University",
  "Bethune-Cookman University",
  "Albany State University",
  "Lincoln University",
  // Art, music & design schools
  "Rhode Island School of Design",
  "Savannah College of Art and Design",
  "Pratt Institute",
  "Parsons School of Design",
  "The New School",
  "School of the Art Institute of Chicago",
  "Maryland Institute College of Art",
  "California Institute of the Arts",
  "ArtCenter College of Design",
  "Fashion Institute of Technology",
  "School of Visual Arts",
  "Ringling College of Art and Design",
  "Otis College of Art and Design",
  "Berklee College of Music",
  "The Juilliard School",
  "Manhattan School of Music",
  "New England Conservatory",
  "The Cooper Union",
  // Service academies & senior military colleges
  "United States Military Academy",
  "United States Naval Academy",
  "United States Air Force Academy",
  "United States Coast Guard Academy",
  "United States Merchant Marine Academy",
  "Virginia Military Institute",
  "The Citadel",
  "Norwich University",
  // Large online & nontraditional universities
  "Southern New Hampshire University",
  "Western Governors University",
  "University of Phoenix",
  "Grand Canyon University",
  "Purdue University Global",
  "University of Maryland Global Campus",
  "Capella University",
  "Walden University",
  "National University",
  "DeVry University",
  "Strayer University",
  "Excelsior University",
  // More public regional & state universities (state systems, directional)
  "California State University, San Marcos",
  "California State University, East Bay",
  "California State University, Stanislaus",
  "California State University, Bakersfield",
  "California State University, Dominguez Hills",
  "Sonoma State University",
  "California State Polytechnic University, Humboldt",
  "SUNY Brockport",
  "SUNY Cortland",
  "SUNY Plattsburgh",
  "SUNY Potsdam",
  "SUNY Oneonta",
  "SUNY Purchase",
  "Buffalo State University",
  "University of Texas Rio Grande Valley",
  "Texas A&M University–Corpus Christi",
  "Texas A&M University–Commerce",
  "West Texas A&M University",
  "Lamar University",
  "Tarleton State University",
  "Angelo State University",
  "University of West Florida",
  "Jacksonville University",
  "Florida Southern College",
  "Indiana University Indianapolis",
  "University of Michigan–Dearborn",
  "University of Michigan–Flint",
  "Ferris State University",
  "Northern Michigan University",
  "Southern Illinois University Edwardsville",
  "University of Wisconsin–Eau Claire",
  "University of Wisconsin–La Crosse",
  "University of Wisconsin–Oshkosh",
  "University of Wisconsin–Whitewater",
  "Minnesota State University, Mankato",
  "St. Cloud State University",
  "University of Minnesota Duluth",
  "Winona State University",
  "Truman State University",
  "Southeast Missouri State University",
  "University of Central Missouri",
  "Emporia State University",
  "Fort Hays State University",
  "University of Nebraska at Kearney",
  "Indiana University of Pennsylvania",
  "Shippensburg University of Pennsylvania",
  "Slippery Rock University of Pennsylvania",
  "Millersville University of Pennsylvania",
  "Kutztown University of Pennsylvania",
  "Bloomsburg University of Pennsylvania",
  "Kean University",
  "William Paterson University",
  "Stockton University",
  "Ramapo College of New Jersey",
  "Monmouth University",
  "Central Connecticut State University",
  "Southern Connecticut State University",
  "Bridgewater State University",
  "Salem State University",
  "University of Southern Maine",
  "Plymouth State University",
  "Keene State College",
  "Longwood University",
  "Western Carolina University",
  "Valdosta State University",
  "Georgia College & State University",
  "Augusta University",
  "Jacksonville State University",
  "University of North Alabama",
  "Tennessee Technological University",
  "Austin Peay State University",
  "Morehead State University",
  "Southeastern Louisiana University",
  "University of Louisiana at Monroe",
  "University of Arkansas at Little Rock",
  "Arkansas Tech University",
  "University of Northern Colorado",
  "Metropolitan State University of Denver",
  "Southern Utah University",
  "Idaho State University",
  // More private, liberal-arts & faith-based universities
  "Wesleyan University",
  "Bennington College",
  "Berea College",
  "St. Lawrence University",
  "Allegheny College",
  "Agnes Scott College",
  "Siena College",
  "St. Bonaventure University",
  "Canisius University",
  "Le Moyne College",
  "Iona University",
  "La Salle University",
  "Widener University",
  "Gannon University",
  "Assumption University",
  "Merrimack College",
  "Endicott College",
  "Western New England University",
  "Saint Michael's College",
  "Champlain College",
  "University of New Haven",
  "University of Hartford",
  "Bryant University",
  "Rider University",
  "John Carroll University",
  "Bellarmine University",
  "Campbell University",
  "Roanoke College",
  "Hampden-Sydney College",
  "Mississippi College",
  "Harding University",
  "Abilene Christian University",
  "Point Loma Nazarene University",
  "Westmont College",
  "Hillsdale College",
  "Grove City College",
  "Messiah University",
  "Gordon College",
  "Cedarville University",
  "University of Puget Sound",
  "Whitworth University",
  "Pacific Lutheran University",
  "Willamette University",
  "University of Redlands",
  "California Lutheran University",
  "University of La Verne",
];
