// Regenerate lib/colleges.ts with the broad set of US four-year institutions.
//
// WHY THIS EXISTS: the College autocomplete should canonicalise wherever a
// just-moved grad actually went (shared college is a top matching signal), so it
// wants the long tail of state regionals, not just the famous names. The hand
// list in lib/colleges.ts is a strong default, but this pulls the exhaustive set
// from a public dataset.
//
// HOW TO RUN (browser-only operator → use a Codespace; this needs network egress
// the Claude Code web sandbox doesn't have):
//   1. Open a Codespace on hangpost-snack
//   2. node scripts/build_colleges.mjs
//   3. git diff lib/colleges.ts   ← REVIEW IT (names become the canonical
//      match strings — sanity-check for "The " prefixes / duplicates)
//   4. commit if it looks right
//
// Source: Hipo/university-domains-list (public, MIT). US institutions only;
// community / technical / junior colleges and non-degree trade schools excluded
// so it stays "above community" (operator's call).

import { writeFileSync } from "node:fs";

const SRC =
  "https://raw.githubusercontent.com/Hipo/university-domains-list/master/world_universities_and_domains.json";

// Heuristic exclusions to keep it four-year ("above community").
const EXCLUDE =
  /(community college|technical college|junior college|county college|city college of|cosmetolog|beauty|barber|truck driv|massage|culinary institute|bartend)/i;

const res = await fetch(SRC);
if (!res.ok) throw new Error(`fetch failed: ${res.status} ${res.statusText}`);
const data = await res.json();

const names = [
  ...new Set(
    data
      .filter((x) => x.country === "United States" && x.name && !EXCLUDE.test(x.name))
      .map((x) => x.name.trim()),
  ),
].sort((a, b) => a.localeCompare(b));

const body = names.map((n) => `  ${JSON.stringify(n)},`).join("\n");

const out = `/** US colleges & universities for the College autocomplete.
 *
 * GENERATED by scripts/build_colleges.mjs — do not hand-edit; re-run the script.
 * Source: Hipo/university-domains-list (public). US institutions only;
 * community / technical / junior colleges excluded. ${names.length} entries.
 *
 * The connections engine matches \`college\` by EXACT string equality, so this
 * list canonicalises the common case; the ComboField free-text fallback covers
 * anything unlisted, so an unlisted school never blocks sign-up. */
export const COLLEGES: readonly string[] = [
${body}
];
`;

writeFileSync(new URL("../lib/colleges.ts", import.meta.url), out);
console.log(`Wrote lib/colleges.ts with ${names.length} institutions.`);
